# Disable the status bar so that we behave more like screen
set -g status off

# Set the prefix to C-a so we're more like screen
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Reload the session
unbind r
bind r source-file ~/.tmux.conf \; display "Reloading ~/.tmux.conf"

# Expand the history to something reasonable
set -g history-limit 10000

set-option -g set-titles on
set-option -g set-titles-string "#S:#I:#W"

# Keybinds
#run-shell ~/git-local-repos/tmux-plugins/tmux-sensible/sensible.tmux

# Sometimes tmux doesn't detect it is on a terminal capable of 256 colors
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ',xterm-256color:Tc:sitm=\E[3m'
