#!/bin/bash

# vim: filetype=bash

# From the excellent answer here:
#
# https://unix.stackexchange.com/questions/108699/documentation-on-less-termcap-variables
#
# Termcap terminfo
#
# ks      smkx      make the keypad send commands
# ke      rmkx      make the keypad send digits
# vb      flash     emit visual bell
# mb      blink     start blink
# md      bold      start bold
# me      sgr0      turn off bold, blink and underline
# so      smso      start standout (reverse video)
# se      rmso      stop standout
# us      smul      start underline
# ue      rmul      stop underline

# Yes, I realize I could use calls to tput, but that's a bundle of subshells and
# I don't want to do that on smaller embedded systems

export LESS_TERMCAP_mb=$'\e[1m\e[33m'
export LESS_TERMCAP_md=$'\e[1m\e[36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_so=$'\e[97\e[44m'
export LESS_TERMCAP_se=$'\e[27m\e[0m'
export LESS_TERMCAP_us=$'\e[4m\e[1m\e[37m'
export LESS_TERMCAP_ue=$'\e[24m\e[0m'
export LESS_TERMCAP_mr=$'\e[7m'
export LESS_TERMCAP_mh=$'\e[2m'
export LESS_TERMCAP_ZN=''
export LESS_TERMCAP_ZV=''
export LESS_TERMCAP_ZO=''
export LESS_TERMCAP_ZW=''
export GROFF_NO_SGR=1

